name: couldai_user_app
description: "A comprehensive messaging app with chat, updates, communities, and calls."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  intl_phone_number_input: ^0.7.3+1
  pin_code_fields: ^8.0.1

  # For calls and media
  agora_rtc_engine: ^6.2.6
  path_provider: ^2.1.2
  record: ^5.0.4

  # For swipe gestures
  flutter_slidable: ^3.0.1

  # For carousel
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
    - family: NotoSansBengali
      fonts:
        - asset: fonts/NotoSansBengali-Regular.ttf
        - asset: fonts/NotoSansBengali-Bold.ttf
          weight: 700
